include(GetOpenSSL)
add_subdirectory(${CMAKE_SOURCE_DIR}/3rd/srt ${CMAKE_CURRENT_BINARY_DIR}/srt EXCLUDE_FROM_ALL)

set (SRT_SRC_HAICRYPT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/srt/haicrypt)
set (SRT_SRC_SRTCORE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/srt/srtcore)
set (SRT_SRC_COMMON_DIR ${CMAKE_CURRENT_SOURCE_DIR}/srt/common)
#set (SRT_SRC_TOOLS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/srt/tools)
#set (SRT_SRC_TEST_DIR ${CMAKE_CURRENT_SOURCE_DIR}/srt/test)
include_directories(${SRT_SRC_COMMON_DIR} ${SRT_SRC_SRTCORE_DIR} ${SRT_SRC_HAICRYPT_DIR})

target_include_directories(${TARGET_srt}_static INTERFACE
    ${SRT_SRC_COMMON_DIR}
    ${SRT_SRC_SRTCORE_DIR}
    ${SRT_SRC_HAICRYPT_DIR}
    ${CMAKE_CURRENT_BINARY_DIR}/srt
)

add_library(3rd::srt ALIAS ${TARGET_srt}_static)

